from flask import Flask, request, jsonify
import sqlite3, secrets, string, datetime, boto3
from mailjet_rest import Client
from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment, LiveEnvironment
from paypalcheckoutsdk.orders import OrdersGetRequest

# ----------------------------
# CONFIGURATION
# ----------------------------
app = Flask(__name__)

PAYPAL_CLIENT_ID = "TA_CLE_PAYPAL"
PAYPAL_SECRET = "TON_SECRET_PAYPAL"
PAYPAL_MODE = "sandbox"  # ou "live"

MAILJET_API_KEY = "TA_CLE_MAILJET"
MAILJET_SECRET_KEY = "TON_SECRET_MAILJET"

AWS_ACCESS_KEY = "TA_CLE_AWS"
AWS_SECRET_KEY = "TON_SECRET_AWS"
AWS_BUCKET = "ton-bucket-s3"
AWS_REGION = "eu-west-3"  # Paris

FILE_KEY = "monfichier.pdf"  # fichier S3 à vendre


# ----------------------------
# BASE DE DONNÉES
# ----------------------------
def db():
    conn = sqlite3.connect("codes.db")
        conn.row_factory = sqlite3.Row
            return conn


            # Initialisation table
            def init_db():
                conn = db()
                    conn.execute("""
                            CREATE TABLE IF NOT EXISTS access_codes (
                                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                    email TEXT NOT NULL,
                                                                code TEXT NOT NULL,
                                                                            status TEXT NOT NULL,
                                                                                        expires_at TEXT NOT NULL,
                                                                                                    created_at TEXT NOT NULL,
                                                                                                                used_at TEXT
                                                                                                                        )
                                                                                                                            """)
                                                                                                                                conn.commit()


                                                                                                                                init_db()


                                                                                                                                # ----------------------------
                                                                                                                                # FONCTION : générer un code
                                                                                                                                # ----------------------------
                                                                                                                                def generate_code(length=12):
                                                                                                                                    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
                                                                                                                                        code = "".join(secrets.choice(alphabet) for _ in range(length))
                                                                                                                                            return "-".join(code[i:i+4] for i in range(0, len(code), 4))


                                                                                                                                            # ----------------------------
                                                                                                                                            # CONFIGURATION MAILJET
                                                                                                                                            # ----------------------------
                                                                                                                                            mailjet = Client(auth=(MAILJET_API_KEY, MAILJET_SECRET_KEY), version='v3.1')


                                                                                                                                            def send_code_email(email, code, expires_at):
                                                                                                                                                message = {
                                                                                                                                                        "Messages": [{
                                                                                                                                                                    "From": {"Email": "support@tonsite.com", "Name": "Support"},
                                                                                                                                                                                "To": [{"Email": email}],
                                                                                                                                                                                            "Subject": "Votre code d’accès",
                                                                                                                                                                                                        "HTMLPart": f"""
                                                                                                                                                                                                                        <h3>Merci pour votre achat</h3>
                                                                                                                                                                                                                                        <p>Voici votre code d’accès :</p>
                                                                                                                                                                                                                                                        <h2>{code}</h2>
                                                                                                                                                                                                                                                                        <p>Lien de validation : https://tonsite.com/accèshttps://tonsite.com/accès</a></p>
                                                                                                                                                                                                                                                                                        <p>Code valable jusqu’au {expires_at}.</p>
                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                            }]
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                    mailjet.send.create(data=message)


                                                                                                                                                                                                                                                                                                                    # ----------------------------
                                                                                                                                                                                                                                                                                                                    # CONFIG PAYPAL SDK
                                                                                                                                                                                                                                                                                                                    # ----------------------------
                                                                                                                                                                                                                                                                                                                    if PAYPAL_MODE == "sandbox":
                                                                                                                                                                                                                                                                                                                        environment = SandboxEnvironment(client_id=PAYPAL_CLIENT_ID, client_secret=PAYPAL_SECRET)
                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                            environment = LiveEnvironment(client_id=PAYPAL_CLIENT_ID, client_secret=PAYPAL_SECRET)

                                                                                                                                                                                                                                                                                                                            paypal_client = PayPalHttpClient(environment)


                                                                                                                                                                                                                                                                                                                            # ----------------------------
                                                                                                                                                                                                                                                                                                                            # ENDPOINT : webhook PayPal
                                                                                                                                                                                                                                                                                                                            # ----------------------------
                                                                                                                                                                                                                                                                                                                            @app.post("/webhook/paypal")
                                                                                                                                                                                                                                                                                                                            def paypal_webhook():
                                                                                                                                                                                                                                                                                                                                body = request.json
                                                                                                                                                                                                                                                                                                                                    order_id = body.get("resource", {}).get("id")

                                                                                                                                                                                                                                                                                                                                        if not order_id:
                                                                                                                                                                                                                                                                                                                                                return jsonify({"error": "No order ID"}), 400

                                                                                                                                                                                                                                                                                                                                                    # Vérifier la commande PayPal
                                                                                                                                                                                                                                                                                                                                                        request_order = OrdersGetRequest(order_id)
                                                                                                                                                                                                                                                                                                                                                            response = paypal_client.execute(request_order)

                                                                                                                                                                                                                                                                                                                                                                payer_email = response.result.payer.email_address

                                                                                                                                                                                                                                                                                                                                                                    # Générer code
                                                                                                                                                                                                                                                                                                                                                                        code = generate_code()
                                                                                                                                                                                                                                                                                                                                                                            expires_at = (datetime.datetime.utcnow() + datetime.timedelta(days=7)).isoformat()

                                                                                                                                                                                                                                                                                                                                                                                conn = db()
                                                                                                                                                                                                                                                                                                                                                                                    conn.execute("""
                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO access_codes (email, code, status, expires_at, created_at)
                                                                                                                                                                                                                                                                                                                                                                                                    VALUES (?, ?, 'unused', ?, datetime('now'))
                                                                                                                                                                                                                                                                                                                                                                                                        """, (payer_email, code, expires_at))
                                                                                                                                                                                                                                                                                                                                                                                                            conn.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                send_code_email(payer_email, code, expires_at)
                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonify({"status": "ok"})


                                                                                                                                                                                                                                                                                                                                                                                                                    # ----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                    # ENDPOINT : valider un code
                                                                                                                                                                                                                                                                                                                                                                                                                    # ----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                    @app.post("/validate")
                                                                                                                                                                                                                                                                                                                                                                                                                    def validate_code():
                                                                                                                                                                                                                                                                                                                                                                                                                        data = request.json
                                                                                                                                                                                                                                                                                                                                                                                                                            email = data.get("email")
                                                                                                                                                                                                                                                                                                                                                                                                                                code = data.get("code")

                                                                                                                                                                                                                                                                                                                                                                                                                                    conn = db()
                                                                                                                                                                                                                                                                                                                                                                                                                                        row = conn.execute("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT * FROM access_codes WHERE email=? AND code=?
                                                                                                                                                                                                                                                                                                                                                                                                                                                    """, (email, code)).fetchone()

                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not row:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonify({"ok": False, "error": "Code invalide"}), 400

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if row["status"] != "unused":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return jsonify({"ok": False, "error": "Code déjà utilisé"}), 400

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if datetime.datetime.fromisoformat(row["expires_at"]) < datetime.datetime.utcnow():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return jsonify({"ok": False, "error": "Code expiré"}), 400

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Marque comme utilisé
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.execute("UPDATE access_codes SET status='used', used_at=datetime('now') WHERE id=?", (row["id"],))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Génére URL S3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            s3 = boto3.client(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "s3",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            aws_access_key_id=AWS_ACCESS_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aws_secret_access_key=AWS_SECRET_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            region_name=AWS_REGION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url = s3.generate_presigned_url(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "get_object",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Params={"Bucket": AWS_BUCKET, "Key": FILE_KEY},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ExpiresIn=60 * 15   # 15 minutes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonify({"ok": True, "download_url": url})


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # LANCER LE SERVEUR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ----------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.run(port=5000, debug=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        